/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости сервиса */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Метрики Prometheus
         * @description HTTP RPS/latency по маршрутам + бизнес-метрики чата/графа (этап 7, ADR-008).
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход: выдаёт JWT (HS256) и создаёт сессию в PG */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Саморегистрация: роль viewer (только PUBLIC), JWT выдаётся сразу
         * @description Открытая регистрация умышленно даёт минимальную роль viewer.
         *
         *     Расширение доступа (analyst/admin) — только через администратора:
         *     POST /admin/users. Аудит: auth.register.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль текущего пользователя по Bearer-токену */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запустить ingestion корпуса (background task) */
        post: operations["start_ingest_admin_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статус последнего/текущего прогона ingestion */
        get: operations["ingest_status_admin_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущее наполнение хранилищ: Qdrant, Neo4j, PostgreSQL (агрегаты) */
        get: operations["storage_stats_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список учётных записей (без секретов) */
        get: operations["list_users_admin_users_get"];
        put?: never;
        /**
         * Создать учётную запись с указанной ролью
         * @description Роль задаёт метки доступа: viewer→PUBLIC, analyst→PUBLIC+INTERNAL, admin→все.
         */
        post: operations["add_user_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить учётную запись (по умолчанию мягко — деактивация; ?hard=true — физически)
         * @description hard=false (дефолт): деактивация — вход заблокирован, история/аудит целы.
         *     hard=true: физическое удаление строки users c чисткой FK-зависимостей
         *     (chat_messages → chat_sessions → sessions) и обезличиванием audit_log
         *     (user_id=NULL, события сохраняются). Qdrant/Neo4j не затрагиваются.
         *     Защиты: нельзя удалить себя; нельзя удалить последнего активного админа.
         *     Имя освобождается только при hard=true (при soft имя остаётся занятым).
         */
        delete: operations["delete_user_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /**
         * Сменить роль пользователя (метки доступа пересчитаются из роли)
         * @description Права применяются сразу: clearances резолвятся из БД на каждом запросе,
         *     повторный вход не требуется. Смена собственной роли запрещена (защита от
         *     случайной потери последнего админа).
         */
        patch: operations["change_user_role_admin_users__user_id__patch"];
        trace?: never;
    };
    "/admin/users/{user_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Деактивировать/реактивировать учётную запись (мягкое отключение)
         * @description Мягкое отключение: is_active=false блокирует вход (login → 401) и
         *     инвалидирует существующие JWT (любой запрос → 401), история и аудит целы.
         *     Реактивация возвращает доступ без создания новых сущностей.
         */
        patch: operations["set_user_status_admin_users__user_id__status_patch"];
        trace?: never;
    };
    "/admin/acts/{act_id}/clearance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Перекатегоризация акта: сменить гриф (Neo4j + payload чанков Qdrant)
         * @description Ручная перекатегоризация (бэклог п.4). Метка меняется синхронно в двух
         *     хранилищах: Neo4j Act.clearance (метаданные) и payload всех Qdrant-точек
         *     акта - pre-fetch ACL ретриверов читает метку именно из payload. Доступ
         *     пересчитывается мгновенно, перезапуск/переиндексация не нужны.
         */
        patch: operations["change_act_clearance_admin_acts__act_id__clearance_patch"];
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вопрос агенту GraphRAG (SSE-стриминг или JSON при stream=false)
         * @description Конвейер: guardrails -> planner -> retrieval (вектор+граф, ACL pre-fetch) -> fusion -> rerank -> generate -> evaluate (re-plan <= APP_AGENT_MAX_ITERATIONS) -> guardrail_out (проверка цитат).
         *
         *     При stream=true возвращает text/event-stream: события `status`, `token`, `done`, `error` (формат - event:\ndata:\n\n). При stream=false - обычный JSON.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acts/{act_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Полный текст акта с метаданными (доступ по метке грифа) */
        get: operations["act_content_api_acts__act_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActClearanceUpdate
         * @description Ручная перекатегоризация акта админом (бэклог п.4).
         *
         *     Обновляет метку синхронно в обоих хранилищах: Neo4j (метаданные) и Qdrant
         *     (payload всех чанков - фильтр pre-fetch ACL читает метку именно оттуда).
         * @example {
         *       "clearance": "SECRET"
         *     }
         */
        ActClearanceUpdate: {
            /**
             * Clearance
             * @enum {string}
             */
            clearance: "PUBLIC" | "INTERNAL" | "SECRET";
        };
        /**
         * ActContentResponse
         * @description Полный текст акта, собранный из чанков векторного хранилища.
         *
         *     Выдаётся только если метка акта входит в ACL пользователя (бэклог п.5).
         * @example {
         *       "act": {
         *         "act_id": "920000001",
         *         "clearance": "PUBLIC",
         *         "date": "15.03.2001",
         *         "doc_number": "920000001-ФЗ",
         *         "status": "Действует без изменений",
         *         "title": "Об акционерных обществах"
         *       },
         *       "chunk_count": 1,
         *       "full_text": "Статья 1. ..."
         *     }
         */
        ActContentResponse: {
            act: components["schemas"]["ActOut"];
            /** Chunk Count */
            chunk_count: number;
            /** Full Text */
            full_text: string;
        };
        /**
         * ActOut
         * @description Метаданные акта из графа знаний.
         */
        ActOut: {
            /** Act Id */
            act_id: string;
            /** Title */
            title: string;
            /** Doc Number */
            doc_number?: string | null;
            /** Date */
            date?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Clearance
             * @enum {string}
             */
            clearance: "PUBLIC" | "INTERNAL" | "SECRET";
        };
        /**
         * ChatRequest
         * @description Запрос к агенту; ``stream=False`` возвращает обычный JSON (Postman/нагрузка).
         */
        ChatRequest: {
            /**
             * Message
             * @description Вопрос пользователя (санитайзер и guardrails применяются на сервере)
             * @example Какие требования к раскрытию информации эмитентами?
             */
            message: string;
            /**
             * Session Id
             * @description Идентификатор диалога; None - начать новый диалог
             */
            session_id?: string | null;
            /**
             * Stream
             * @description true - SSE-поток событий, false - JSON
             * @default true
             */
            stream: boolean;
        };
        /**
         * DeleteUserResponse
         * @description Итог удаления учётной записи (DELETE /admin/users/{id}?hard=true|false).
         * @example {
         *       "mode": "deleted",
         *       "user_id": "...",
         *       "username": "qa_x"
         *     }
         * @example {
         *       "mode": "deactivated",
         *       "user_id": "...",
         *       "username": "qa_x"
         *     }
         */
        DeleteUserResponse: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "deactivated" | "deleted";
        };
        /**
         * ErrorResponse
         * @description Тело ошибки домена/валидации.
         */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestStartResponse */
        IngestStartResponse: {
            /**
             * State
             * @default started
             * @constant
             */
            state: "started";
            /**
             * Message
             * @default Прогон ingestion запущен
             */
            message: string;
        };
        /** IngestStatusResponse */
        IngestStatusResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "idle" | "running" | "done" | "error";
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Stats */
            stats?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Stage */
            stage?: ("parse" | "model" | "processing" | "done" | "error") | null;
            /** Files Done */
            files_done?: number | null;
            /** Files Total */
            files_total?: number | null;
            /** Chunks Done */
            chunks_done?: number | null;
        };
        /**
         * LoginRequest
         * @description Тело запроса логина.
         * @example {
         *       "password": "analyst123",
         *       "username": "analyst"
         *     }
         */
        LoginRequest: {
            /**
             * Username
             * @description Имя пользователя
             */
            username: string;
            /**
             * Password
             * @description Пароль (bcrypt на сервере)
             */
            password: string;
        };
        /**
         * MeResponse
         * @description Профиль текущего пользователя (по Bearer-токену).
         */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /**
             * Clearances
             * @description Метки доступа роли (ACL для pre-fetch фильтров)
             */
            clearances: string[];
        };
        /**
         * Neo4jStats
         * @description Узлы и рёбра графа знаний (по меткам онтологии ADR-006).
         */
        Neo4jStats: {
            /** Acts */
            acts: number;
            /** Authorities */
            authorities: number;
            /** Topics */
            topics: number;
            /** Concepts */
            concepts: number;
            /** Relationships */
            relationships: number;
        };
        /**
         * PostgresStats
         * @description Учётные записи и история диалогов.
         */
        PostgresStats: {
            /** Users */
            users: number;
            /** Chat Sessions */
            chat_sessions: number;
            /** Chat Messages */
            chat_messages: number;
        };
        /**
         * QdrantStats
         * @description Наполнение векторного хранилища.
         */
        QdrantStats: {
            /** Collection */
            collection: string;
            /** Points */
            points: number;
        };
        /**
         * StorageStatsResponse
         * @description Снимок текущего наполнения хранилищ (без прогресса прогонов).
         */
        StorageStatsResponse: {
            qdrant: components["schemas"]["QdrantStats"];
            neo4j: components["schemas"]["Neo4jStats"];
            postgres: components["schemas"]["PostgresStats"];
        };
        /**
         * TokenResponse
         * @description Успешный логин: JWT + метаданные сессии.
         * @example {
         *       "access_token": "eyJhbGciOiJIUzI1NiIs...",
         *       "expires_in": 1800,
         *       "role": "analyst",
         *       "token_type": "bearer",
         *       "username": "analyst"
         *     }
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires In
             * @description TTL токена, секунды
             */
            expires_in: number;
            /** Username */
            username: string;
            /** Role */
            role: string;
        };
        /**
         * UserCreate
         * @description Создание учётной записи администратором.
         * @example {
         *       "password": "qa123456",
         *       "role": "viewer",
         *       "username": "qa_viewer"
         *     }
         */
        UserCreate: {
            /**
             * Username
             * @description Имя пользователя (уникально)
             */
            username: string;
            /**
             * Password
             * @description Пароль (bcrypt на сервере)
             */
            password: string;
            /**
             * Role
             * @description Роль определяет метки доступа
             * @default viewer
             * @enum {string}
             */
            role: "viewer" | "analyst" | "admin";
        };
        /**
         * UserOut
         * @description Учётная запись без секретов.
         */
        UserOut: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "analyst" | "admin";
            /**
             * Clearances
             * @description Метки доступа роли
             */
            clearances: string[];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRoleUpdate
         * @description Смена роли пользователя админом; метки доступа пересчитаются из роли.
         * @example {
         *       "role": "analyst"
         *     }
         */
        UserRoleUpdate: {
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "analyst" | "admin";
        };
        /**
         * UserStatusUpdate
         * @description Неактивный пользователь не может войти; существующие JWT отклоняются
         * @example {
         *       "is_active": false
         *     }
         */
        UserStatusUpdate: {
            /** Is Active */
            is_active: boolean;
        };
        /** UsersListResponse */
        UsersListResponse: {
            /** Users */
            users: components["schemas"]["UserOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Неверные учётные данные или пользователь деактивирован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Имя пользователя занято */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неверный формат имени/пароля */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Токен отсутствует, недействителен или истёк */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    start_ingest_admin_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStartResponse"];
                };
            };
            /** @description Не admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Прогон уже идёт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest_status_admin_ingest_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStatusResponse"];
                };
            };
            /** @description Не admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    storage_stats_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageStatsResponse"];
                };
            };
            /** @description Не admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersListResponse"];
                };
            };
            /** @description Не admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_user_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Не admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Имя занято */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_admin_users__user_id__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteUserResponse"];
                };
            };
            /** @description Не admin или попытка удалить себя */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Последний активный админ */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_user_role_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Не admin или попытка сменить собственную роль */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_status_admin_users__user_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Не admin или попытка изменить себя */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Последний активный админ */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_act_clearance_admin_acts__act_id__clearance_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                act_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActClearanceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActOut"];
                };
            };
            /** @description Не admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Акт не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Неизвестная метка доступа */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Нет/невалидный JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    act_content_api_acts__act_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                act_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActContentResponse"];
                };
            };
            /** @description Метка акта выше уровня доступа роли */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Акт не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
